### PR TITLE
Device APIs should not throw errors

### LINKED ISSUE #23: Device APIs should not throw errors.
To-Dos
- While registering a device, the server should not throw an error if the `device_token` is already present.
- While deleting the device, the server should not throw an error if the `device_token` is already deleted.

### PR DESCRIPTION
**Pull request by jaybhoyar**
Closes #23 

- While registering a device, the server should not throw an error if the device_token is already present.
- While deleting the device, the server should not throw an error if the device_token is already deleted.

### CODE REVIEW

**Comment by jaybhoyar** [comment]
@chiraggshah _a Please review.

**Review by chiraggshah — COMMENTED** [review]
@jaybhoyar _a : Looks good. Please add test cases as well.

**Comment by jaybhoyar** [comment]
> @jaybhoyar _a : Looks good. Please add test cases as well.

@chiraggshah _a The device controller has already been added to neeto apps. We'll have to manually update the controller and test cases.

**Comment by chiraggshah** [comment]
@jaybhoyar : How urgently is this fix needed? I think we should convert our gem to an engine so that the controller resides inside the engine and not in the parent app. That way we have total control over the code and dont need to copy over files in the parent.

**Comment by jaybhoyar** [comment]
> @jaybhoyar : How urgently is this fix needed? I think we should convert our gem to an engine so that the controller resides inside the engine and not in the parent app. That way we have total control over the code and dont need to copy over files in the parent.

@chiraggshah _a We needed this fix in neetoDesk, neetoChat and neetoInvoice's production apps by today itself. For now, I'll make the changes in these manually. 
About converting the gem to the rails engine, yes it will give us more control over the code and shall be easy to manage.

**Comment by jaybhoyar** [comment]
Fixed in https://github.com/bigbinary/neeto_notifications/pull/26

**Pull request closed without merging**
